name: 'Dependabot'
on:
  pull_request: {}
permissions:
  contents: 'read'
jobs:
  automerge:
    name: 'Auto-Merge'
    runs-on: 'ubuntu-latest'
    if: github.event.pull_request.user.login == 'dependabot[bot]' && github.repository == 'go-webauthn/webauthn'
    permissions:
      contents: 'write'
    steps:
      - name: 'Harden Runner'
        uses: step-security/harden-runner@5ef0c079ce82195b2a36a210272d6b661572d83e # v2.14.2
        with:
          egress-policy: 'audit'
      - name: 'Dependabot Fetch Metadata'
        id: 'metadata'
        uses: dependabot/fetch-metadata@21025c705c08248db411dc16f3619e6b5f9ea21a
        with:
          github-token: '${{ secrets.GITHUB_TOKEN }}'
      - name: 'Enable Auto-Merge'
        run: |
          gh pr merge --auto --squash "$PR_URL"
        env:
          PR_URL: '${{ github.event.pull_request.html_url }}'
          GH_TOKEN: '${{ secrets.GITHUB_TOKEN }}'
