name: 'Dependabot'
on:
  pull_request: {}
permissions:
  contents: 'read'
jobs:
  automerge:
    name: 'Auto-Merge'
    runs-on: 'ubuntu-latest'
    permissions:
      contents: 'read'
      pull-requests: 'write'
    if: github.event.pull_request.user.login == 'dependabot[bot]' && github.repository == 'go-webauthn/webauthn'
    steps:
      - name: 'Harden Runner'
        uses: step-security/harden-runner@ec9f2d5744a09debf3a187a3f4f675c53b671911 # v2.13.0
        with:
          egress-policy: 'audit'
      - name: 'Dependabot Fetch Metadata'
        id: 'metadata'
        uses: dependabot/fetch-metadata@08eff52bf64351f401fb50d4972fa95b9f2c2d1b
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
      - name: 'Enable Auto-Merge'
        run: |
          gh pr merge --auto --squash "$PR_URL"
        env:
          PR_URL: ${{ github.event.pull_request.html_url }}
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
