name: 'Scorecards'
on:
  branch_protection_rule: {}
  schedule:
    - cron: '20 7 * * 2'
  push:
    branches:
     - 'master'
permissions: 'read-all'
jobs:
  analysis:
    name: 'OpenSSF'
    runs-on: 'ubuntu-latest'
    permissions:
      security-events: 'write'
      id-token: 'write'
      contents: 'read'
      actions: 'read'
    steps:
      - name: 'Harden Runner'
        uses: step-security/harden-runner@95d9a5deda9de15063e7595e9719c11c38c90ae2 # v2.13.2
        with:
          egress-policy: 'audit'
      - name: 'Checkout'
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
        with:
          persist-credentials: false
      - name: 'Analyze'
        uses: ossf/scorecard-action@4eaacf0543bb3f2c246792bd56e8cdeffafb205a # v2.4.3
        with:
          results_file: 'results.sarif'
          results_format: 'sarif'
          publish_results: true
      - name: 'Upload'
        uses: actions/upload-artifact@330a01c490aca151604b8cf639adc76d48f6c5d4 # v5.0.0
        with:
          name: 'SARIF file'
          path: 'results.sarif'
          retention-days: 5
      - name: 'Upload to Code Scanning Dashboard'
        uses: github/codeql-action/upload-sarif@0499de31b99561a6d14a36a5f662c2a54f91beee # v3.29.5
        with:
          sarif_file: 'results.sarif'
