name: 'Scorecard'
on:
  branch_protection_rule: {}
  schedule:
    - cron: '20 7 * * 2'
  push:
    branches:
      - 'master'
permissions: 'read-all'
jobs:
  analysis:
    name: 'Analysis'
    runs-on: 'ubuntu-latest'
    permissions:
      security-events: 'write'
      id-token: 'write'
      contents: 'read'
      actions: 'read'
    steps:
      - name: 'Harden Runner'
        uses: step-security/harden-runner@5ef0c079ce82195b2a36a210272d6b661572d83e # v2.14.2
        with:
          egress-policy: 'audit'
      - name: 'Checkout'
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false
      - name: 'Run'
        uses: ossf/scorecard-action@4eaacf0543bb3f2c246792bd56e8cdeffafb205a # v2.4.3
        with:
          results_file: 'results.sarif'
          results_format: 'sarif'
          publish_results: true
      - name: 'Upload'
        uses: actions/upload-artifact@b7c566a772e6b6bfb58ed0dc250532a479d7789f # v6.0.0
        with:
          name: 'SARIF file'
          path: 'results.sarif'
          retention-days: 5
      - name: 'Upload to Code Scanning Dashboard'
        uses: github/codeql-action/upload-sarif@9e907b5e64f6b83e7804b09294d44122997950d6 # v4.32.3
        with:
          sarif_file: 'results.sarif'
